# Generated by Django 4.2.30 on 2026-09-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_twitter_profile_linkedin_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
